spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  datasource:
    url: jdbc:h2:tcp://localhost/~/critt
    username: sa
    password:
    driver-class-name: org.h2.Driver
  main:
    allow-circular-references: true

  profiles:
    include: db

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
