server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  datasource:
    url: jdbc:h2:tcp://localhost/~/critt
    username: sa
    password:
    driver-class-name: org.h2.Driver
  main:
    allow-circular-references: true

  profiles:
    include: db

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true


  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            client-id: 654898016967-ga4did0cpou4r9ckv0r7ho42arkrtlc1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

          naver:
            client-id: L61z2MvnsWFQfYi7kRi2
            client-secret: C7WDt44jj5
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: abc570fb116bd926266e60e2e34149bb
            redirect-uri: http://localhost:3000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
            token_uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

file:
  dir: C:\Users\SSAFY\Desktop\파일저장

OPENVIDU_URL: https://i9d201.p.ssafy.io:8443/
OPENVIDU_SECRET: CRITCRIT


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

app:
  auth:
    token-secret: critservicecritservice


